import { html } from '@webjskit/core';

const env = (globalThis as any).process?.env ?? {};
const WEBSITE_URL = env.WEBSITE_URL || 'https://webjs.dev';
const DOCS_URL = env.DOCS_URL || 'https://docs.webjs.dev';

export const metadata = {
  title: 'Webjs UI — AI-first component library',
  description: 'An AI-first component library. Two-tier composition — class-helper functions for visuals, custom elements only where state matters. Source-copied into your project. Works in webjs, Next, Astro, Vite, vanilla — any project with Tailwind v4.',
  themeColor: '#1c1613',
  openGraph: { type: 'website', title: 'Webjs UI', description: 'AI-first component library' },
};

export default function Layout({ children }: { children: any }) {
  // Don't wrap in <!doctype><html><head><body> — the framework's SSR
  // pipeline already emits those (along with title, meta, importmap,
  // and modulepreload tags derived from `metadata`). Adding a manual
  // shell produces a second <head> block that the HTML parser drops
  // — which used to silently disable the favicon, the inline <style>,
  // and the Tailwind stylesheet link.
  //
  // The pipeline auto-hoists <link>, <style>, <script>, and <meta>
  // elements returned here into the real <head>. Other markup goes
  // into <body>.
  return html`
    <link rel="icon" href="/public/favicon.svg" type="image/svg+xml" />
    <link rel="icon" href="/public/favicon.png" type="image/png" />
    <link rel="apple-touch-icon" href="/public/favicon.png" />
    <link rel="stylesheet" href="/public/tailwind.css" />
    <style>
          :root {
            color-scheme: light dark;
            --fg:            oklch(0.18 0.015 60);
            --fg-muted:      oklch(0.42 0.02 65);
            --fg-subtle:     oklch(0.62 0.015 70);
            --bg:            oklch(0.985 0.008 80);
            --bg-elev:       oklch(1 0 0);
            --bg-subtle:     oklch(0.96 0.008 80);
            --bg-sunken:     oklch(0.94 0.008 80);
            --border:        oklch(0.88 0.01 75 / 0.95);
            --border-strong: oklch(0.78 0.01 75 / 0.95);
            --accent:        oklch(0.58 0.15 55);
            --accent-hover:  oklch(0.5 0.15 55);
            --accent-fg:     oklch(1 0 0);
            --accent-tint:   oklch(0.58 0.15 55 / 0.08);
            --font-sans:  -apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            --font-serif: ui-serif, 'Iowan Old Style', 'Palatino Linotype', Palatino, Georgia, Cambria, serif;
            --font-mono:  ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Monaco, Consolas, monospace;
          }
          @media (prefers-color-scheme: dark) {
            :root:not([data-theme='light']) {
              --fg:            oklch(0.96 0.015 60);
              --fg-muted:      oklch(0.72 0.02 60);
              --fg-subtle:     oklch(0.55 0.02 60);
              --bg:            oklch(0.14 0.01 55);
              --bg-elev:       oklch(0.18 0.01 55);
              --bg-subtle:     oklch(0.16 0.01 55);
              --bg-sunken:     oklch(0.11 0.008 55);
              --border:        oklch(0.26 0.012 55 / 0.9);
              --border-strong: oklch(0.38 0.012 55 / 0.9);
              --accent:        oklch(0.78 0.14 55);
              --accent-hover:  oklch(0.85 0.14 55);
              --accent-fg:     oklch(0.15 0.01 55);
              --accent-tint:   oklch(0.78 0.14 55 / 0.12);
            }
          }
          html, body { margin: 0; font-family: var(--font-sans); }
          body { background: var(--bg); color: var(--fg); font: 400 16px/1.55 var(--font-sans); -webkit-font-smoothing: antialiased; }
          a { color: var(--accent); text-decoration: none; }
          a:hover { color: var(--accent-hover); }
          /* .text-muted-foreground / .text-foreground / .bg-background /
             .bg-muted are now generated by Tailwind from the @theme block
             (mapping to shadcn tokens). Don't override here — the manual
             overrides would clash with component previews. */
          /* Code-block surface: always dark for clear differentiation against
             the page background, regardless of light/dark mode. Mirrors how
             the shadcn website renders pre blocks (zinc-950 in light mode). */
          .bg-code, pre.bg-muted, pre {
            background: oklch(0.18 0.01 55);
            color: oklch(0.92 0.008 80);
            border: 1px solid color-mix(in oklch, oklch(0.18 0.01 55) 80%, var(--border));
          }
          pre code { color: inherit; }
          /* bg-primary / text-primary etc. are now generated by Tailwind from
             the @theme block in public/input.css and map to shadcn-neutral
             tokens (so component previews look like shadcn). The docs chrome
             uses raw var(--accent) for the webjs brand orange. */
          /* All bg-* and hover:bg-* utilities now come from Tailwind's generated
             output (input.css → @theme block → shadcn tokens). No manual
             overrides — they would clash with component-preview colours. */
          .border, .border-b, .border-t { border-color: var(--border); border-style: solid; border-width: 0; }
          .border { border-width: 1px; }
          .border-b { border-bottom-width: 1px; }
          .border-t { border-top-width: 1px; }
          pre code { font-family: var(--font-mono); font-size: 12.5px; }
          .prose h1 { font: 700 clamp(2rem, 1.5rem + 1.6vw, 2.6rem)/1.15 var(--font-serif); letter-spacing: -0.025em; color: var(--accent); margin: 0 0 16px; }
          .prose h2 { font: 700 1.4rem/1.2 var(--font-serif); margin: 40px 0 12px; padding-top: 24px; border-top: 1px solid var(--border); }
          .prose p, .prose li { color: var(--fg); margin: 12px 0; }
          .prose code { font-family: var(--font-mono); font-size: 0.9em; padding: 1px 5px; background: var(--bg-subtle); border-radius: 4px; }
          .prose pre { background: var(--bg-sunken); padding: 16px; border-radius: 8px; overflow-x: auto; }
          .prose pre code { background: transparent; padding: 0; }
          /* Thin themed horizontal scrollbar — only visible when content overflows. */
          .scrollbar-thin { scrollbar-width: thin; scrollbar-color: transparent transparent; }
          .scrollbar-thin:hover, .scrollbar-thin:focus-within { scrollbar-color: var(--border-strong) transparent; }
          .scrollbar-thin::-webkit-scrollbar { height: 8px; width: 8px; }
          .scrollbar-thin::-webkit-scrollbar-track { background: transparent; }
          .scrollbar-thin::-webkit-scrollbar-thumb { background: transparent; border-radius: 4px; transition: background 120ms ease; }
          .scrollbar-thin:hover::-webkit-scrollbar-thumb,
          .scrollbar-thin:focus-within::-webkit-scrollbar-thumb { background: var(--border-strong); }
          .scrollbar-thin::-webkit-scrollbar-thumb:hover { background: var(--fg-subtle); }

          .announce { width: 100%; background: var(--accent-tint); border-bottom: 1px solid var(--border); padding: 8px 16px; text-align: center; font-size: 13px; }
          .announce .tag { display: inline-block; font: 700 10px/1 var(--font-mono); letter-spacing: 0.12em; text-transform: uppercase; color: var(--accent); background: color-mix(in oklch, var(--accent) 15%, transparent); padding: 3px 7px; border-radius: 999px; margin-right: 8px; vertical-align: middle; }
    </style>
    <div class="announce">
          <span class="tag">v1</span>
          <a href=${WEBSITE_URL} target="_blank" rel="noopener noreferrer" class="inline-flex items-center gap-1.5">
            Part of webjs - the AI-first, web components framework
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
              <path d="M5 12h14"></path><path d="m12 5 7 7-7 7"></path>
            </svg>
          </a>
        </div>
        <header class="border-b">
          <div class="max-w-5xl mx-auto flex flex-wrap min-h-14 items-center px-4 sm:px-6 py-2 gap-x-4 gap-y-2 sm:gap-6">
            <a href="/" class="font-bold text-base inline-flex items-center" style="color: var(--fg)">
              <span style="display:inline-block; width:22px; height:22px; border-radius:6px; background:linear-gradient(135deg, var(--accent), color-mix(in oklch, var(--accent) 55%, var(--fg))); vertical-align:middle; margin-right:8px"></span>
              Webjs UI
            </a>
            <nav class="flex flex-wrap items-center gap-x-4 gap-y-2 text-sm sm:ml-auto sm:gap-x-5" style="color: var(--fg-muted)">
              <a href="/" style="color: var(--fg-muted)">Components</a>
              <a href="/docs" style="color: var(--fg-muted)">Docs</a>
              <a class="hidden sm:inline" href=${WEBSITE_URL} target="_blank" style="color: var(--fg-muted)">Webjs</a>
              <a href="https://github.com/vivek7405/webjs" target="_blank" style="color: var(--fg-muted)">GitHub</a>
            </nav>
          </div>
        </header>
        <main class="max-w-5xl mx-auto px-6 py-10">${children}</main>
        <footer class="border-t mt-20 py-8 text-center" style="color: var(--fg-subtle); font-size: 13px">
          <div class="max-w-5xl mx-auto px-6">
            <a href="https://webjs.dev" target="_blank">Webjs</a> ·
            <a href=${DOCS_URL} target="_blank">Docs</a> ·
            <a href="https://github.com/vivek7405/webjs" target="_blank">GitHub</a>
          </div>
        </footer>
      </body>
    </html>
  `;
}
