/**
 * The agent context pack: the WHOLE example gallery and the WHOLE agent skill,
 * concatenated into ONE file (`.agents/context-pack.md`) that the scaffold's
 * CLAUDE.md imports, so an agent starts a session with every context layer
 * already in context instead of spending turns opening files, and so quality
 * never depends on which file it decides to open.
 *
 * It keeps every layer intact (the gallery is studied, the skill is read,
 * `node_modules/@webjsdev/*` stays the source of truth); it only makes the
 * first two cheap, and it is paid once per hour at cache-write price. Loaded before the user's message, the pack sits in
 * the model's cached prompt prefix, so it is paid once at cache-write price and
 * then read at a tenth of that on every later turn. A host that runs many
 * builds from one image (Crisp) can put it in the system prompt instead, where
 * separate builds share the same cached prefix.
 *
 * The content is BYTE-STABLE: fixed roots walked in sorted order, no
 * timestamps, no absolute paths, so two apps scaffolded by the same CLI version
 * get the same pack and the same cache key. The pack is generated once at `webjs create` from the files just
 * written, so it shows exactly the code this app was scaffolded with; it is
 * kept by `gallery:clear`, so the patterns stay in context after the demos go.
 */
import { existsSync } from 'node:fs';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, extname } from 'node:path';

/**
 * Everything the gallery ships, in a fixed order: the example app first, then
 * every feature demo, then every gallery module. Sorted paths within each
 * group, so two apps scaffolded by the same CLI get the same bytes.
 */
export const PACK_CODE_ROOTS = ['app/examples', 'app/features', 'modules'];

/** The whole agent skill: SKILL.md, then every reference by name. */
export const PACK_SKILL_ROOT = '.agents/skills/webjs';

/** Gallery files the pack leaves out: browser tests need a runner, not reading. */
const SKIP = /(^|\/)browser\/|\.test\.(ts|js)$/;

const fence = (rel) => ({ '.ts': 'ts', '.js': 'js', '.md': 'md', '.mjs': 'js' }[extname(rel)] || '');

/**
 * App-relative paths of every file under `rel` (recursive), sorted.
 * @param {string} appDir
 * @param {string} rel
 * @returns {Promise<string[]>}
 */
async function filesUnder(appDir, rel) {
  const dir = join(appDir, rel);
  if (!existsSync(dir)) return [];
  const { readdir } = await import('node:fs/promises');
  const entries = await readdir(dir, { recursive: true, withFileTypes: true });
  return entries
    .filter((e) => e.isFile())
    .map((e) => join(e.parentPath || dir, e.name).slice(appDir.length + 1).replace(/\\/g, '/'))
    .sort();
}

/**
 * Build the pack text for an app.
 * @param {string} appDir
 * @returns {Promise<string>}
 */
export async function buildContextPack(appDir) {
  const out = [
    '# WebJs context pack',
    '',
    'Generated by `webjs create` from this app\'s own files, loaded at the start of every session so they are already in your context: the WHOLE agent skill (`SKILL.md` and every reference) and the WHOLE example gallery (`app/examples`, `app/features` and the gallery\'s `modules/`, as shipped, before `gallery:clear`). Reading a file below IS reading it: the context-gathering steps in AGENTS.md (read the skill, study the gallery) are done here, so do not open these files again. `node_modules/@webjsdev/*` stays the source of truth for an exact API and is on disk.',
    '',
  ];
  const seen = new Set();
  const add = async (rel) => {
    if (seen.has(rel) || !existsSync(join(appDir, rel))) return;
    seen.add(rel);
    const text = (await readFile(join(appDir, rel), 'utf8')).replace(/\s+$/, '');
    const f = fence(rel);
    out.push(`### \`${rel}\``, '', f === 'md' ? text : `\`\`\`\`${f}\n${text}\n\`\`\`\``, '');
  };
  out.push('## The example gallery', '');
  for (const root of PACK_CODE_ROOTS) {
    for (const rel of await filesUnder(appDir, root)) {
      if (!SKIP.test(rel) && /\.(ts|js|mjs|md)$/.test(rel)) await add(rel);
    }
  }
  out.push('## The agent skill', '');
  await add(`${PACK_SKILL_ROOT}/SKILL.md`);
  for (const rel of await filesUnder(appDir, `${PACK_SKILL_ROOT}/references`)) if (rel.endsWith('.md')) await add(rel);
  return out.join('\n') + '\n';
}

/**
 * Write `.agents/context-pack.md` for an app.
 * @param {string} appDir
 * @returns {Promise<string>} the app-relative path written
 */
export async function writeContextPack(appDir) {
  const rel = '.agents/context-pack.md';
  await mkdir(join(appDir, '.agents'), { recursive: true });
  await writeFile(join(appDir, rel), await buildContextPack(appDir));
  return rel;
}
