import { html } from '@webjsdev/core';

export const metadata = { title: 'Server Actions | webjs' };

export default function ServerActions() {
  return html`
    <h1>Server Actions</h1>
    <p>Server actions are <strong>async functions that run exclusively on the server</strong> but can be imported and called from client-side web components as if they were local functions. webjs rewrites the import at serve time so the browser receives a thin RPC stub instead of the real implementation. The result is full-stack type safety with zero manual API layer.</p>

    <h2>Defining a Server Action: the Two-Marker Convention</h2>
    <p>Server-side files use <strong>two complementary markers</strong>. The combination determines behaviour:</p>

    <table>
      <thead>
        <tr><th>File</th><th><code>'use server'</code>?</th><th>What it is</th></tr>
      </thead>
      <tbody>
        <tr><td><code>*.server.{js,ts}</code></td><td>yes</td><td><strong>Server action.</strong> Source-protected AND RPC-callable: client imports are rewritten to RPC stubs that POST to <code>/__webjs/action/&lt;hash&gt;/&lt;fn&gt;</code>.</td></tr>
        <tr><td><code>*.server.{js,ts}</code></td><td>no</td><td><strong>Server-only utility.</strong> Source-protected; browser imports get a throw-at-load stub. Use for the Drizzle connection (<code>db/connection.server.ts</code>), session helpers, password hashing.</td></tr>
        <tr><td>Plain <code>.ts</code></td><td>yes</td><td><strong>Lint violation</strong> (<code>use-server-needs-extension</code>). The directive alone is silently ignored, and the file serves to the browser as plain source. Rename to add the <code>.server.</code> infix.</td></tr>
        <tr><td>Plain <code>.ts</code></td><td>no</td><td>Browser-safe; standard behaviour.</td></tr>
      </tbody>
    </table>

    <p>Bottom line: the <code>.server.{js,ts}</code> infix is the path-level boundary (the HTTP layer refuses to serve the source to the browser, full stop). The <code>'use server'</code> directive is what registers the exported functions as RPC endpoints. You need both for a server action.</p>

    <h3>Server action (path boundary + RPC marker)</h3>
    <pre>// modules/posts/actions/create-post.server.ts
'use server';
import { eq } from 'drizzle-orm';
import { db } from '../../../db/connection.server.ts';
import { posts } from '../../../db/schema.server.ts';

export async function createPost(input: { title: string; body: string }) {
  const [post] = await db.insert(posts).values(input).returning();
  return post;
}

export async function deletePost(id: number) {
  await db.delete(posts).where(eq(posts.id, id));
  return { ok: true };
}</pre>

    <h3>Server-only utility (path boundary, no RPC)</h3>
    <p>Drop the <code>'use server'</code> directive when the file should be unreachable from the browser but is NOT called as a server action (the Drizzle connection, password hashing, helpers used by other server files). Browser imports throw at load time.</p>

    <pre>// db/connection.server.ts
import * as schema from './schema.server.ts';

const url = process.env.DATABASE_URL?.replace(/^file:/, '') ?? 'db/dev.db';
const g = globalThis as unknown as { __webjs_db?: unknown };

async function open() {
  if ((globalThis as { Bun?: unknown }).Bun) {
    const { Database } = await import('bun:sqlite');
    const { drizzle } = await import('drizzle-orm/bun-sqlite');
    return drizzle({ client: new Database(url), relations: schema.relations });
  }
  const { default: Database } = await import('better-sqlite3');
  const { drizzle } = await import('drizzle-orm/better-sqlite3');
  return drizzle({ client: new Database(url), relations: schema.relations });
}

export const db = (g.__webjs_db ??= await open()) as Awaited&lt;ReturnType&lt;typeof open&gt;&gt;;</pre>

    <p><strong>Do not import a server-only utility directly into a page, layout, or component.</strong> The stub throws when the module <em>loads</em> (not when called), so it works during SSR but crashes when a component hydrates or a page/layout module loads in the browser. Use server-only utilities <em>inside</em> server actions, <code>route.{js,ts}</code> handlers, or <code>middleware</code> (which only ever run on the server). A page reaches server logic by importing a <code>'use server'</code> <strong>action</strong> instead: its RPC stub loads safely on the client and isn't even called there.</p>

    <h2>How the Import Rewrite Works</h2>
    <p>When the browser requests a server module's URL (e.g. <code>/actions/posts.server.ts</code>), the dev server intercepts the request. Instead of serving the real file (which contains database calls, secrets, etc.), it generates and serves a <strong>client stub</strong>:</p>

    <pre>// Generated by webjs (you never see this file)
import { stringify as __wjStringify, parse as __wjParse } from '@webjsdev/core';

async function __rpc(fn, args) {
  const body = await __wjStringify(args);
  // No CSRF token: the browser attaches Origin / Sec-Fetch-Site to a
  // same-origin POST itself, and the server verifies it.
  const res = await fetch('/__webjs/action/a1b2c3d4e5/' + fn, {
    method: 'POST',
    headers: { 'content-type': 'application/vnd.webjs+json' },
    credentials: 'same-origin',
    body
  });
  const ct = res.headers.get('content-type') || '';
  const text = await res.text();
  const parsed = ct.includes('application/vnd.webjs+json')
    ? __wjParse(text)
    : (ct.includes('application/json') ? JSON.parse(text) : text);
  if (!res.ok) {
    const msg = (parsed &amp;&amp; parsed.error) || ('webjs action ' + fn + ' -> ' + res.status);
    throw new Error(msg);
  }
  return parsed;
}

export const createPost = (...args) => __rpc('createPost', args);
export const deletePost = (...args) => __rpc('deletePost', args);</pre>

    <p>The hash (<code>a1b2c3d4e5</code>) is a SHA-256 digest of the file's absolute path, computed when the action index is first built (lazily, on the first request, not at boot). The stub's function signatures match the original exports, so TypeScript sees the real types through the import.</p>

    <h2>Full-Stack Type Safety</h2>
    <p>Because the browser's import statement points at the real <code>.server.ts</code> file, TypeScript's language server resolves types from the original source. Your editor shows the correct parameter types, return types, and JSDoc comments. The rewrite happens only at runtime in the browser, so the type checker never sees the stub.</p>

    <pre>// components/post-form.ts
import { WebComponent, html, css } from '@webjsdev/core';
import { createPost } from '../actions/posts.server.ts';
//                        ^-- TS sees: (input: { title: string; body: string }) => Promise&lt;Post&gt;

export class PostForm extends WebComponent {
  static styles = css\`:host { display: block; }\`;

  async handleSubmit(e: Event) {
    e.preventDefault();
    const form = (e.target as HTMLFormElement);
    const title = (form.elements.namedItem('title') as HTMLInputElement).value;
    const body = (form.elements.namedItem('body') as HTMLTextAreaElement).value;
    const post = await createPost({ title, body });
    //    ^-- post is typed as Post, with real Date objects (not strings)
    this.dispatchEvent(new CustomEvent('created', { detail: post }));
  }

  render() {
    return html\`
      &lt;form @submit=\${(e: Event) =&gt; this.handleSubmit(e)}&gt;
        &lt;input name="title" placeholder="Title" required /&gt;
        &lt;textarea name="body" placeholder="Write something..." required&gt;&lt;/textarea&gt;
        &lt;button type="submit"&gt;Publish&lt;/button&gt;
      &lt;/form&gt;
    \`;
  }
}
PostForm.register('post-form');</pre>

    <h2>The Wire Format</h2>
    <p>Server actions use <strong>webjs's built-in serializer</strong> (a pure-ESM, dependency-free implementation in <code>@webjsdev/core</code>) for the RPC wire, not plain <code>JSON.stringify</code>. The content type is <code>application/vnd.webjs+json</code>. Rich JavaScript types survive the round trip:</p>
    <ul>
      <li><code>Date</code> objects: arrive as real <code>Date</code> instances, not ISO strings</li>
      <li><code>Map</code> and <code>Set</code>: preserved as their native types</li>
      <li><code>BigInt</code>: preserved (plain JSON throws on BigInt)</li>
      <li><code>undefined</code>: distinguished from <code>null</code></li>
      <li><code>NaN</code>, <code>Infinity</code>, <code>-0</code>: preserved (plain JSON drops these)</li>
      <li><code>Error</code>: name + message + stack preserved</li>
      <li><code>TypedArray</code> (Int8...Float64), <code>ArrayBuffer</code>, <code>DataView</code>: inlined as base64</li>
      <li><code>Blob</code>, <code>File</code>, <code>FormData</code>: including binary content (file uploads through actions just work)</li>
      <li><code>Symbol.for(...)</code> registered symbols: preserved (local symbols throw a clear error)</li>
      <li>Reference cycles + shared references: preserved by id</li>
      <li>Nested combinations of all the above</li>
    </ul>
    <p>The stub serialises function arguments with <code>await stringify(args)</code> and deserialises the response with <code>parse(text)</code>. The server does the inverse. This is invisible to the developer, so you work with native types on both sides. The serializer is async because Blob/File/FormData require an <code>await arrayBuffer()</code>. For payloads without binary the async cost is just one Promise tick.</p>

    <h2>HTTP Verbs, Caching, and Streaming</h2>
    <p>A server action is a POST by default, but it can declare richer HTTP semantics through reserved sibling exports the framework reads statically, the same way a page declares <code>export const revalidate</code>. The call site never changes (you still write <code>await getUser(7)</code>); only the transport does. webjs needs this where React and Next do not: webjs has no server/client component split, so both reads and writes flow through the one action mechanism.</p>
    <p><strong>One callable function per configured file.</strong> A <code>.server.ts</code> file that declares any of these config exports must export exactly one callable. A second callable in the same file is a <code>webjs check</code> error.</p>

    <h3>Choosing the verb</h3>
    <p><code>export const method</code> selects the HTTP verb (absent means POST, so existing actions are unchanged):</p>
    <pre>// modules/users/queries/get-user.server.ts
'use server';
export const method = 'GET';
export async function getUser(id: number) {
  return db.query.users.findFirst({ where: { id } });
}</pre>
    <p>The verb changes the wire, not your code. A <strong>GET</strong> rides its arguments in the URL query (with an automatic POST fallback above a 4KB cap), is CSRF-exempt, and carries cache headers (below). A <strong>mutation</strong> (POST / PUT / PATCH / DELETE) sends the rich serialized body (DELETE rides the URL), is CSRF-protected, and reports cache invalidation (below). A request whose method does not match the declared verb gets a <code>405</code> with an <code>Allow</code> header.</p>

    <h3>Caching a GET (and invalidating it)</h3>
    <p>A GET action can opt into response caching, and a mutation can evict it by tag:</p>
    <pre>// a cached, tagged GET
'use server';
export const method = 'GET';
export const cache = 60;                          // seconds; or { maxAge, swr, public }
export const tags = (id: number) => ['user:' + id];
export async function getUser(id: number) { return db.query.users.findFirst({ where: { id } }); }</pre>
    <pre>// a mutation evicts the tags it touches
'use server';
export const invalidates = (id: number) => ['user:' + id];
export async function updateUser(id: number, patch: Partial&lt;User&gt;) { /* ... */ }</pre>
    <p>A cached GET carries <code>Cache-Control</code> plus a weak <code>ETag</code> (answering <code>If-None-Match</code> with a <code>304</code>) and an <code>X-Webjs-Tags</code> header. When a mutation completes (it did not throw), the framework evicts its <code>invalidates</code> tags from the server cache and reports them via <code>X-Webjs-Invalidate</code>, so the client browser-cache coordinator revalidates a later read.</p>
    <p><strong>Safety.</strong> <code>cache</code> with <code>public: true</code> SHARES one response across all users, keyed only by URL plus arguments. Use it ONLY for data identical for every visitor, never a session or per-user read. This is the same safety rule as a page's <code>export const revalidate</code>. The default (private) cache is per-response and safe.</p>

    <h3>Per-action middleware</h3>
    <p><code>export const middleware</code> runs a chain around the action on BOTH the RPC and the <code>route.ts</code> boundary. Each entry is <code>async (ctx, next) => result</code>; it short-circuits by returning an <code>ActionResult</code> instead of calling <code>next()</code>, and accumulates context the action reads via <code>actionContext()</code> from <code>@webjsdev/server</code>, with no signature change to the action.</p>
    <pre>'use server';
import { requireAuth } from '#lib/mw.server.ts';
export const middleware = [requireAuth];
export async function deletePost(id: number) { /* ... */ }</pre>

    <h3>Streaming results</h3>
    <p>An action that RETURNS a <code>ReadableStream</code>, an async iterable, or an async generator (any verb) streams its chunks over the single RPC response instead of buffering. The call site consumes it with <code>for await</code>:</p>
    <pre>// the action
'use server';
export async function* streamTokens(n: number) {
  for (let i = 0; i &lt; n; i++) yield 'token ' + i;
}

// a component
for await (const chunk of await streamTokens(8)) {
  this.text.set(this.text.get() + chunk);
}</pre>
    <p>Each chunk is rich-serialized as it is yielded (back-pressure is respected, and the source generator is cancelled on a client disconnect or a superseded render). Detection is purely on the return value, so there is no config export. A streamed result is never cached, ETagged, or seeded; a mutation still emits <code>X-Webjs-Invalidate</code>. A mid-stream throw surfaces as an error from the iterable (the production message only, since the 200 status is already sent).</p>

    <h3>Cancellation</h3>
    <p>An action reads the request's <code>AbortSignal</code> via <code>actionSignal()</code> (from <code>@webjsdev/server</code>) to stop work on a client disconnect or abort. On the client, a superseded <code>async render()</code> automatically ABORTS the previous render's in-flight action fetch, so a fast-typing user does not pile up stale requests. Outside an action, <code>actionSignal()</code> returns a never-aborting signal, so a direct server-to-server call stays safe.</p>

    <h3>No re-fetch on hydration (SSR seeding)</h3>
    <p>Each server-action result invoked during a (non-streamed) SSR render is serialized into the page, and the generated stub reads that seed on its FIRST client call, so a shipping component does not re-issue the RPC on hydration. A later refetch or argument change still goes to the network. The seed is keyed by action hash plus function plus serialized arguments, consumed once, and fail-open (a miss degrades to a normal RPC, never wrong data). It is on by default; opt out with <code>"webjs": { "seed": false }</code> or <code>WEBJS_SEED=0</code>.</p>

    <h2>CSRF Protection</h2>
    <p>Every <em>mutating</em> server action RPC call (POST / PUT / PATCH / DELETE) is protected against Cross-Site Request Forgery by a cross-origin check, the model Remix 3 and Go 1.25 use. A GET action is CSRF-exempt (as noted above), since it is a read and does not mutate state. The check works as follows:</p>
    <ol>
      <li>The server reads <code>Sec-Fetch-Site</code>, a fetch-metadata header the browser sets on every request and page JavaScript cannot forge. <code>same-origin</code> and <code>none</code> (a direct navigation) pass.</li>
      <li>When <code>Sec-Fetch-Site</code> is absent (an older browser), it falls back to comparing the <code>Origin</code> host against the request host (honoring <code>x-forwarded-host</code> behind a proxy).</li>
      <li>A cross-site request is rejected with a 403, unless its origin is listed in <code>webjs.allowedOrigins</code> (for reverse-proxy or multi-domain setups).</li>
    </ol>
    <p>This works because a browser stamps a forged cross-site request with the attacker's origin (or <code>Sec-Fetch-Site: cross-site</code>), which fails the host match. There is no token, no cookie, and no server-side session store. A useful consequence: SSR responses carry no <code>Set-Cookie</code>, so a page that opts into a public <code>Cache-Control</code> is CDN-edge-cacheable.</p>

    <h2>REST Endpoints from Server Actions</h2>
    <p>A server action is RPC-callable from client components. To ALSO reach the same function over plain HTTP (from curl, a mobile app, or another service), put it behind a <code>route.ts</code> handler, the framework's first-class HTTP route. The action stays a normal <code>'use server'</code> function; the route imports it and calls it.</p>

    <pre>// modules/posts/actions/create-post.server.ts
'use server';
import { db } from '../../../db/connection.server.ts';
import { posts } from '../../../db/schema.server.ts';

export async function createPost({ title, body }: { title: string; body: string }) {
  const [post] = await db.insert(posts).values({ title, body }).returning();
  return post;
}</pre>

    <pre>// app/api/posts/route.ts
import { createPost } from '../../../modules/posts/actions/create-post.server.ts';

export async function POST(req: Request) {
  const body = await req.json();
  const post = await createPost(body);
  return Response.json(post);
}</pre>

    <p>Now <code>createPost</code> is reachable two ways, both backed by the exact same function:</p>
    <ul>
      <li><strong>From a client component:</strong> <code>import { createPost } from '.../create-post.server.ts'</code> is auto-rewritten to an RPC stub, CSRF-protected, encoded with the webjs rich serializer.</li>
      <li><strong>From curl or another service:</strong> <code>POST /api/posts</code> with a JSON body, served by the <code>route.ts</code> handler.</li>
    </ul>

    <h3>The route() Adapter</h3>
    <p>For the common case (merge query + route params + JSON body into one input object, run an optional validator, JSON-respond the result), the <code>route()</code> helper from <code>@webjsdev/server</code> writes that handler for you in one line. The hand-written <code>route.ts</code> above is always available for full control (custom headers, content negotiation, streaming).</p>

    <pre>// app/api/posts/route.ts
import { route } from '@webjsdev/server';
import { createPost } from '../../../modules/posts/actions/create-post.server.ts';

export const POST = route(createPost);

// app/api/posts/[slug]/route.ts
import { route } from '@webjsdev/server';
import { getPost } from '../../../../modules/posts/queries/get-post.server.ts';

// ctx.params.slug merges into the action input
export const GET = route(getPost);</pre>

    <h3>Validating the Input</h3>
    <p>A boundary validator runs server-side before the action body. On the RPC path, declare it as the <code>validate</code> config export beside the action (issue #245). For a <code>route()</code> endpoint, pass it as the <code>validate</code> option. It receives the action's first argument and may throw to reject, return a structured <code>{ success: false, fieldErrors }</code> envelope (a <code>422</code> over HTTP, a <code>result.fieldErrors</code> object over RPC), or return a transformed input value.</p>

    <pre>// modules/posts/actions/create-post.server.ts
'use server';
import { z } from 'zod';
import { db } from '../../../db/connection.server.ts';
import { posts } from '../../../db/schema.server.ts';

const CreatePostSchema = z.object({
  title: z.string().min(1).max(200),
  body: z.string().min(1).max(20000),
});

// the RPC boundary reads this config export
export const validate = CreatePostSchema.parse;

export async function createPost(input: { title: string; body: string }) {
  const [post] = await db.insert(posts).values(input).returning();
  return post;
}</pre>

    <pre>// app/api/posts/route.ts: the REST boundary passes the same validator
import { route } from '@webjsdev/server';
import { createPost } from '../../../modules/posts/actions/create-post.server.ts';
import { z } from 'zod';

const CreatePostSchema = z.object({
  title: z.string().min(1).max(200),
  body: z.string().min(1).max(20000),
});

export const POST = route(createPost, { validate: CreatePostSchema.parse });</pre>

    <p>When a thrown validator fails over HTTP, the response is <code>400 { "error": "...", "issues": [...] }</code>. If the thrown error has an <code>issues</code> property (as zod and valibot errors do), it is passed through for structured client-side handling. A structured envelope failure is a <code>422</code>.</p>

    <h3>CORS for a REST Endpoint</h3>
    <p>If your endpoint will be called from a different origin (e.g. a mobile app or a partner's frontend), wrap the <code>route.ts</code> handler in the <code>cors()</code> middleware from <code>@webjsdev/server</code>, or apply <code>cors()</code> in <code>middleware.ts</code> for the path. See the <a href="/docs/middleware">middleware</a> docs.</p>

    <p><strong>Important:</strong> a <code>route.ts</code> REST endpoint is <em>not</em> CSRF-protected (only the internal RPC path is). A mutating REST endpoint is designed for external consumers who authenticate via bearer tokens, API keys, or signed requests. Add your own auth in a middleware or inside the function body.</p>

    <h2>ActionResult&lt;T&gt; Envelope Pattern</h2>
    <p>A recommended convention for server actions is to return a discriminated union instead of throwing errors:</p>

    <pre>type ActionResult&lt;T&gt; =
  | { success: true; data: T }
  | { success: false; error: string; status: number };

export async function createPost(input: unknown): Promise&lt;ActionResult&lt;Post&gt;&gt; {
  const user = await currentUser();
  if (!user) return { success: false, error: 'Not signed in', status: 401 };

  if (!input || typeof input !== 'object') {
    return { success: false, error: 'Invalid input', status: 400 };
  }
  const { title, body } = input as { title: string; body: string };
  if (!title) return { success: false, error: 'title is required', status: 400 };

  const [post] = await db.insert(posts).values({ title, body, authorId: user.id }).returning();
  return { success: true, data: post };
}</pre>

    <p>This pattern makes error handling explicit on the client side without relying on try/catch. The caller checks <code>result.success</code> and branches accordingly. It also works naturally over a <code>route.ts</code> REST endpoint, where the caller receives the same JSON shape.</p>

    <h2>Error Sanitisation in Production</h2>
    <p>When a server action throws (rather than returning an error envelope), webjs catches the exception and returns a JSON error response:</p>
    <ul>
      <li><strong>Development:</strong> the response includes both the error message and the full stack trace, making debugging easy.</li>
      <li><strong>Production:</strong> only the error message is included. Stack traces are never sent to the client. If the thrown error has no message, a generic "Internal server error" is returned. The full error is always logged server-side.</li>
    </ul>
    <p>This prevents accidental leakage of file paths, database schemas, or other implementation details to end users.</p>

    <h2>Complete Example</h2>
    <p>Here is the full flow from defining a server action to calling it from a component and exposing it over REST via a <code>route.ts</code>:</p>

    <pre>// 1. Define the server action
// actions/todos.server.ts
'use server';

interface Todo { id: number; text: string; done: boolean; createdAt: Date; }
const todos: Todo[] = [];
let nextId = 1;

export async function addTodo({ text }: { text: string }) {
  const todo: Todo = { id: nextId++, text, done: false, createdAt: new Date() };
  todos.push(todo);
  return todo;
}

export async function listTodos() {
  return todos;
}

// 1b. Expose them over REST with the route() adapter
// app/api/todos/route.ts
import { route } from '@webjsdev/server';
import { addTodo, listTodos } from '../../../actions/todos.server.ts';

export const GET = route(listTodos);
export const POST = route(addTodo);

// 2. Call from a web component
// components/todo-app.ts
import { WebComponent, html, css } from '@webjsdev/core';
import { addTodo, listTodos } from '../actions/todos.server.ts';

export class TodoApp extends WebComponent {
  static styles = css\`
    :host { display: block; max-width: 400px; }
    ul { list-style: none; padding: 0; }
    li { padding: 8px 0; border-bottom: 1px solid #eee; }
    .date { color: #999; font-size: 12px; }
  \`;

  todos = signal&lt;{ id: number; text: string; createdAt: Date }[]&gt;([]);

  async connectedCallback() {
    super.connectedCallback();
    const todos = await listTodos();
    this.todos.set(todos);
    // todos[0].createdAt is a real Date (the rich serializer preserved it)
  }

  async handleAdd(e: Event) {
    e.preventDefault();
    const input = this.shadowRoot!.querySelector('input') as HTMLInputElement;
    const todo = await addTodo({ text: input.value });
    this.todos.set([...this.todos.get(), todo]);
    input.value = '';
  }

  render() {
    return html\`
      &lt;form @submit=\${(e: Event) =&gt; this.handleAdd(e)}&gt;
        &lt;input placeholder="What needs doing?" required /&gt;
        &lt;button&gt;Add&lt;/button&gt;
      &lt;/form&gt;
      &lt;ul&gt;
        \${this.todos.get().map(t =&gt; html\`
          &lt;li&gt;
            \${t.text}
            &lt;span class="date"&gt;\${t.createdAt.toLocaleDateString()}&lt;/span&gt;
          &lt;/li&gt;
        \`)}
      &lt;/ul&gt;
    \`;
  }
}
TodoApp.register('todo-app');

// 3. Call the REST endpoint from curl
// curl -X POST http://localhost:8080/api/todos \\
//   -H 'Content-Type: application/json' \\
//   -d '{"text":"Buy milk"}'
// => {"id":1,"text":"Buy milk","done":false,"createdAt":"2026-04-15T..."}</pre>

    <h2>Plain HTML forms as an alternative (the page action)</h2>
    <p>Server actions called via JS RPC are the right tool when you need typed return values back in the component (the createPost example above returns a <code>Post</code> object). For the simpler "submit form, server processes, render the result" flow, the framework's <strong>page action</strong> is the cleaner fit. A <code>page.{js,ts}</code> may export an <code>action</code> alongside its default render function. A non-GET/HEAD submission to that page's own URL runs the action (inside the page's segment middleware), so a plain <code>&lt;form method="POST"&gt;</code> works with JavaScript disabled AND through the client router, same UI either way. You write no <code>route.ts</code> and no hand-rolled <code>new Response(...)</code>.</p>
    <p>The action receives <code>{ request, params, searchParams, url, formData }</code> (<code>formData</code> is the already-parsed body, <code>request</code> is the raw Request) and returns an <code>ActionResult</code>. The framework interprets the result.</p>
    <pre>// app/posts/page.ts
import { html } from '@webjsdev/core';
import { createPost } from '../../modules/posts/actions/create-post.server.ts';

// Runs only on the server. Receives the already-parsed formData.
export async function action({ formData }: { formData: FormData }) {
  const title = String(formData.get('title') || '').trim();
  const body = String(formData.get('body') || '').trim();
  const values = { title, body };
  const fieldErrors: Record&lt;string, string&gt; = {};
  if (!title) fieldErrors.title = 'Title is required';
  if (body.length &lt; 10) fieldErrors.body = 'Body is too short';
  if (Object.keys(fieldErrors).length) {
    return { success: false, fieldErrors, values, status: 422 };
  }
  const post = await createPost({ title, body });
  return { success: true, redirect: \`/posts/\${post.id}\` };
}

export default function NewPost({ actionData }: {
  actionData?: { fieldErrors?: Record&lt;string, string&gt;; values?: Record&lt;string, string&gt; };
}) {
  const errors = actionData?.fieldErrors || {};
  const values = actionData?.values || {};
  return html\`
    &lt;form method="POST"&gt;
      &lt;input name="title" value=\${values.title || ''} required /&gt;
      \${errors.title ? html\`&lt;p class="error"&gt;\${errors.title}&lt;/p&gt;\` : ''}
      &lt;textarea name="body" required&gt;\${values.body || ''}&lt;/textarea&gt;
      \${errors.body ? html\`&lt;p class="error"&gt;\${errors.body}&lt;/p&gt;\` : ''}
      &lt;button&gt;Publish&lt;/button&gt;
    &lt;/form&gt;
  \`;
}</pre>
    <p>How the framework interprets the returned <code>ActionResult</code>:</p>
    <ul>
      <li><strong>Success</strong> (<code>{ success: true, redirect? }</code>, or any non-failure result) is a <code>303 See Other</code> to <code>result.redirect</code> if present, else the page's own path (Post/Redirect/Get, so a reload does not resubmit). <code>result.redirect</code> must be a same-site local path (a single leading <code>/</code>); for a real external redirect throw <code>redirect(absoluteUrl)</code>.</li>
      <li><strong>Failure</strong> (<code>{ success: false }</code>, or a <code>fieldErrors</code>, or an <code>error</code>) re-SSRs the SAME page with <code>status</code> (default <code>422</code>) and the result on <code>ctx.actionData</code>. The page reads <code>actionData.fieldErrors.&lt;name&gt;</code> for messages and <code>actionData.values.&lt;name&gt;</code> to repopulate native <code>&lt;input value=...&gt;</code>, so the user's typed input survives.</li>
    </ul>
    <p>With JavaScript off this is a native round-trip (the browser submits, follows the 303, or renders the 422). With JavaScript on the client router applies the 422 in place (no reload, typed input preserved) and follows the 303 via fetch. Both ends of the progressive-enhancement spectrum from one piece of code, no form library. See the <a href="/docs/client-router">client router</a> docs for the rendering behavior, and <a href="/docs/progressive-enhancement">progressive enhancement</a> for the full write-path pattern.</p>
  `;
}
