import { html } from '@webjsdev/core';

export const metadata = {
  title: 'Troubleshooting | WebJs',
  description:
    'Symptom-keyed fixes for the distinctive WebJs error signatures: throw-at-load server imports, backtick-in-template 500s, TypeScript strip failures, SSR browser-global crashes, the missing-frame swap, and more, each linked to the webjs check rule and the invariant behind it.',
};

export default function Troubleshooting() {
  return html`
    <h1>Troubleshooting</h1>
    <p>webjs's no-build, isomorphic-module model produces a few error signatures you have not seen in a bundled framework: a module that throws at LOAD rather than at call, a 500 from a stray backtick, a strip-time failure that points at a lint rule. This page is keyed by SYMPTOM. Find the error text or the behavior you are seeing, then read the cause and the fix. Most of these are also caught ahead of time by <code>webjs check</code>, so run it first.</p>

    <h2>"Cannot import X from browser code. This file is server-only"</h2>
    <p><strong>Symptom:</strong> the page goes blank and the browser console shows an error thrown at module load, naming a <code>.server</code> file, before any of your code runs.</p>
    <p><strong>Cause:</strong> you imported a server-only utility (a <code>.server.{js,ts}</code> file with NO <code>'use server'</code> directive) directly into a page, layout, or component. The dev server resolves that browser import to a stub whose body throws at the top level, so it fails the instant the module loads, not when you call the function. This is deliberate: it keeps the server source (your database connection, secrets, <code>node:*</code> usage) off the client.</p>
    <p><strong>Fix:</strong> never import a no-<code>'use server'</code> util straight into client-bound code. Use it INSIDE a <code>'use server'</code> action, a <code>route.{js,ts}</code> handler, or <code>middleware.{js,ts}</code> (all server-only), and have the page call that action. A page reaches server logic through an action whose RPC stub loads safely on the client. See <a href="/docs/server-actions">Server Actions</a>. This is framework invariant 1 (the <code>.server</code> boundary). The <code>no-server-import-in-browser-module</code> check rule catches this ahead of time, on any page, layout, or component the build determines will ship to the browser (a display-only page the framework elides is not flagged). A TYPE-ONLY <code>import type { Row } from './x.server.ts'</code> is exempt, because the TypeScript stripper erases it before it reaches the browser, so sharing a derived row type from a <code>.server.ts</code> is safe and is not flagged.</p>

    <h2>A 500 in production from an <code>html</code> template that worked in dev</h2>
    <p><strong>Symptom:</strong> a page renders in dev but 500s in production, or throws a cryptic JavaScript parse error near a template.</p>
    <p><strong>Cause:</strong> a backtick character appears inside an <code>html\`...\`</code> (or <code>css\`...\`</code>) template body, even inside a CSS or HTML comment. A nested backtick closes the tagged-template literal at JavaScript parse time, so the rest of the file is misparsed.</p>
    <p><strong>Fix:</strong> remove the backtick from the template body. If you need a literal backtick in rendered output, build it from a string expression (<code>\${'\`'}</code>) rather than typing it inline. This is framework invariant 9.</p>

    <h2>A 500 at strip time pointing at <code>no-non-erasable-typescript</code></h2>
    <p><strong>Symptom:</strong> a <code>.ts</code> file 500s with a message about TypeScript stripping and the <code>no-non-erasable-typescript</code> rule, or the server refuses to start naming a required Node version.</p>
    <p><strong>Cause:</strong> WebJs strips types with Node 24+'s built-in <code>module.stripTypeScriptTypes</code>, which only erases TYPES. Non-erasable syntax (an <code>enum</code>, a <code>namespace</code> with values, a constructor parameter property, a legacy decorator with <code>emitDecoratorMetadata</code>, or <code>import = require</code>) has no type-only form to strip, so it fails. The Node-version variant means you are on Node below 24, where the built-in strip and recursive <code>fs.watch</code> are unavailable.</p>
    <p><strong>Fix:</strong> set <code>compilerOptions.erasableSyntaxOnly: true</code> in <code>tsconfig.json</code> so the compiler rejects these at edit time, and use the erasable equivalents (a <code>const</code> object plus a union type instead of an <code>enum</code>, an explicit field plus assignment instead of a parameter property). Upgrade to Node 24+ for the version error. See <a href="/docs/typescript">TypeScript</a>. This is framework invariant 10, enforced by the <code>erasable-typescript-only</code> and <code>no-non-erasable-typescript</code> check rules.</p>

    <h2>An SSR crash naming <code>document</code>, <code>window</code>, or a DOM method</h2>
    <p><strong>Symptom:</strong> the server render throws naming a browser global or an <code>HTMLElement</code> method (<code>document</code>, <code>window</code>, <code>localStorage</code>, <code>this.querySelector</code>, <code>this.classList</code>, <code>this.attachShadow</code>), and the page never reaches the browser.</p>
    <p><strong>Cause:</strong> a component touched a genuinely browser-only global in its <code>constructor</code> or <code>render()</code>, both of which run during SSR. The SSR pipeline constructs the component and calls <code>render()</code> on the server, where the live DOM does not exist. (The attribute methods, <code>closest()</code>, and the host IDL reflections ARE backed by a server shim and do not crash; only the live-DOM surface does.)</p>
    <p><strong>Fix:</strong> move browser-only reads (<code>localStorage</code>, viewport, <code>matchMedia</code>, <code>navigator.*</code>) into <code>connectedCallback</code>, which runs only in the browser, then write the value to a signal to refine the first paint. Defaults for the first paint go in the constructor; server-known data comes through the page function as a prop. See <a href="/docs/components">Components</a> and <a href="/docs/progressive-enhancement">Progressive Enhancement</a>. The <code>no-browser-globals-in-render</code> check rule catches this ahead of time.</p>

    <h2>A custom element renders but never reacts to a property change</h2>
    <p><strong>Symptom:</strong> the component paints correctly on first load, but assigning a reactive property later does not re-render it.</p>
    <p><strong>Cause:</strong> you wrote a class-field initializer for a factory-declared reactive property (<code>count: number = 0</code> or <code>count = 0</code> alongside <code>WebComponent({ count: Number })</code>). Under modern class-field semantics that compiles to a define on <code>this</code> AFTER <code>super()</code>, which overwrites the framework's reactive accessor, so subsequent assignments bypass the update.</p>
    <p><strong>Fix:</strong> remove the class-field initializer and set the default by assigning in the <code>constructor</code> after <code>super()</code>. See <a href="/docs/components">Components</a>. The <code>reactive-props-no-class-field</code> check rule flags this.</p>

    <h2>A component method named <code>append</code>, <code>remove</code>, or <code>appendChild</code> silently never runs</h2>
    <p><strong>Symptom:</strong> a handler or helper you defined on a component (an <code>append()</code> click handler, a <code>remove()</code> method) does nothing when called, with no error thrown, and TypeScript did not complain.</p>
    <p><strong>Cause:</strong> WebJs instruments the native DOM mutation methods on every light-DOM host to keep the slot API live, and it installs those interceptors as own properties ON THE ELEMENT INSTANCE. An own instance property shadows a method defined on the class prototype, so the framework's interceptor wins and your same-named class method is never reached. The instrumented names are <code>append</code>, <code>prepend</code>, <code>before</code>, <code>after</code>, <code>replaceWith</code>, <code>replaceChildren</code>, <code>remove</code>, <code>appendChild</code>, <code>insertBefore</code>, <code>removeChild</code>, and <code>replaceChild</code>. TypeScript does not catch it because a shorter override (zero or one argument) is assignable to the native signature.</p>
    <p><strong>Fix:</strong> rename the member to a non-native name (<code>appendRow()</code>, <code>removeItem()</code>) and update its call sites. Only these native mutation members are affected; <code>render()</code> and the lifecycle hooks are meant to be overridden. The <code>no-shadowed-native-member</code> check rule catches this ahead of time (it flags only a real instance method, never a static member, a nested-object property, or a <code>static shadow = true</code> component, whose native shadow slots are not instrumented). See <a href="/docs/components">Components</a>.</p>

    <h2>An error saying a function was interpolated into <code>action=</code>, or that it is not a server action</h2>
    <p><strong>Symptom:</strong> a render fails with <code>a function was interpolated into action=</code>, or with <code>the function in action= is not a server action</code>. The supported binding is an unquoted <code>action=\${fn}</code> on a <code>&lt;form&gt;</code>, where the function is imported from a <code>'use server'</code> module; the first message means the shape was a near-miss the renderer will not stringify, and the second means the shape was right but the function is not an action the server can run. Where that surfaces depends on which render threw. From a <strong>page or layout</strong> it propagates, so the nearest <code>error</code> boundary catches it and the message is visible. From inside a <strong>component</strong> it does not: per-component SSR error isolation contains it, so dev renders an error box in place of the component while production renders the component empty and the page still returns 200. A form that has silently vanished in production, with no error anywhere, is the same bug wearing a disguise; check the server log for the message. In neither case is the action's source emitted.</p>
    <p>Two refinements on "renders the component empty", because both send people looking in the wrong place. The isolation replaces the element through its matching closing tag, so <strong>anything slotted into that component disappears with it</strong>: put the bad form in a shared header or shell and every page returns 200 with an empty body, which reads like a routing failure rather than one broken component. And on a route with a <code>loading.ts</code>, the page renders inside a <code>Suspense</code> boundary after the 200 and the shell are already flushed, where a throw is currently swallowed with <strong>no server log and no error report</strong>; the visitor gets chrome and a blank body, and with JS off the loading skeleton simply stays. That silence is why the log line you are looking for may not exist on that path; it is a known gap rather than intended behaviour.</p>
    <p><strong>Cause:</strong> during SSR an imported <code>'use server'</code> action is the REAL function (the RPC stub exists only in the browser). The supported binding resolves that function's identity instead of stringifying it, but in any OTHER shape <code>action=</code> is an ordinary attribute hole, so stringifying it would write the action's whole body into the HTML every visitor downloads: its logic, the query shapes it builds, and any literal written inside it, a connection string or internal path included.</p>
    <p><strong>Assume outer values are exposed too.</strong> On Node, <code>Function.prototype.toString</code> returns source text, so a module-scope <code>const</code> the body reads appears only as its identifier. That is NOT a guarantee you can rely on: Bun transpiles a module before the engine sees it and can fold a module-scope string literal straight into the body, so the same action reports <code>Authorization: "Bearer sk_live_…"</code> where Node reports <code>Bearer \${VENDOR_API_KEY}</code>. Do not go looking for the rule that decides when it folds. It is a transpiler's internal choice rather than a documented boundary, and two modules on the same Bun version can differ. Whether a secret in an outer binding escapes therefore depends on the runtime and on how the module was transformed, and it is not a boundary worth building a habit on. Treat everything reachable from the action as exposed, which is what the refusal assumes. WebJs refuses rather than emitting it. The refusal covers every shape that is not the binding: an unsupported <code>formaction=</code> shape, <code>action=\${fn}</code> on a tag that is not a <code>&lt;form&gt;</code>, a quoted <code>action="\${fn}"</code> or mixed <code>action="/x/\${fn}"</code> (quoting turns a binding hole back into a plain attribute), and a function wrapped in an array (<code>action=\${[fn]}</code>), which stringifies its elements the same way. One shape it does not cover: a hole inside an HTML comment is emitted raw by the renderer, so commenting a working form out does NOT disable the interpolation, it turns the binding back into a leak. Delete the form rather than commenting around it. <code>.action=\${fn}</code> on a native form is refused at SSR too, even though the property is dropped there, so a page cannot render clean on the server and then throw on hydration, where the reflected IDL attribute would carry the source into the live DOM.</p>
    <p><strong>Two things stay legal</strong>, because neither stringifies its value: a custom element's <code>.action</code> property (an author-defined property, not the reflected IDL attribute a native <code>&lt;form&gt;</code> has, so <code>&lt;my-el .action=\${fn}&gt;</code> is fine), and an unquoted <code>@action=\${fn}</code> event listener, where a function is exactly what is wanted. One qualification on the first: that holds for a plain property, and NOT if the component declares it <code>reflect: true</code>. Reflection is a separate path that writes <code>String(value)</code> into the attribute without passing through the template commit sites this guard covers, so a reflecting <code>action</code> prop still emits the function's source. That path is a general problem with reflecting any function-valued prop rather than an <code>action</code> one, and it is tracked separately. Quoting a binding hole turns it back into a plain attribute, so <code>@action="\${fn}"</code> IS refused; that is the practical reason invariant 4 requires <code>@</code>, <code>.</code> and <code>?</code> holes to be unquoted. <code>?action=\${fn}</code> is refused as well: it never leaked, but a truthy function would silently emit a bare <code>action=""</code>. The HTML spec requires <code>action</code> to be a valid non-empty URL when the attribute is present, so an empty one is a conformance error rather than merely a pointless value. Deleting the attribute is not the fix here, though: a page has no <code>action</code> export, so a form that binds nothing and posts is the 405 described below, conformant and still broken (a bare GET form merely re-renders the page). Bind the action, <code>&lt;form action=\${fn}&gt;</code>, which is what emits the identity the dispatcher reads.</p>
    <p><strong>Fix:</strong> write the binding exactly: an unquoted <code>action=\${importedAction}</code> on the <code>&lt;form&gt;</code> itself, or <code>formaction=\${importedAction}</code> on a <code>&lt;button&gt;</code> inside a bound form, with the function imported from a <code>'use server'</code> module. Use a <code>&lt;button&gt;</code> rather than an <code>&lt;input type="submit"&gt;</code>, whose <code>value</code> is both the identity channel and the visible label. Do not add submitter <code>name</code>, <code>value</code>, <code>form</code>, or static <code>formaction</code> attributes. Do not add <code>method</code> or <code>enctype</code>; the renderer supplies both. A string action is unaffected. See <a href="/docs/server-actions">Server Actions</a> and <a href="/docs/progressive-enhancement">Progressive Enhancement</a>.</p>

    <h2>A form submission answered with a 405</h2>
    <p><strong>Symptom:</strong> submitting a form returns <code>405 Method Not Allowed</code> with <code>Allow: GET, HEAD</code>, and the page itself renders fine on a GET.</p>
    <p><strong>Cause:</strong> the form binds no action. A page has no <code>action</code> export, so a bare <code>&lt;form method="post"&gt;</code> has nothing to run: the url exists and only renders, which is what the 405 says. The other way to get one is binding an action whose file declares <code>export const method = 'GET'</code>; a GET action rides its arguments in the url and skips the CSRF check, so it cannot answer a form POST. That case answers <code>Allow: GET</code>, and <code>webjs check</code>'s <code>form-action-not-a-get-action</code> rule catches it before it ships.</p>
    <p><strong>Fix:</strong> bind the action (<code>&lt;form action=\${submitFeedback}&gt;</code>), or drop the <code>method</code> export from the action's file so it is an ordinary POST.</p>

    <h2>A button submits and the page just re-renders</h2>
    <p><strong>Symptom:</strong> clicking a <code>formaction=\${action}</code> button reloads the same page with a 200, nothing was written, no error appears anywhere, and the address bar has grown a <code>?__webjs_action=</code> parameter.</p>
    <p><strong>Cause:</strong> the enclosing <code>&lt;form&gt;</code> binds no action AND declares no <code>method="post"</code>, so the browser submits it as a GET. (An unbound form that DOES declare <code>method="post"</code> still works, because the identity rides the button's own name/value pair and reaches the server in the body.) A GET sends no body, so the identity the button carries rides the query string instead, and a GET at a page url just renders the page. That is why there is no 405 and no log line. The renderer refuses this shape when it can see both halves in one template, but a submitter inside a COMPONENT is a cannot-tell (the component renders in its own pass with no view of the host page) and cannot-tell has to bind, so a split-across-modules form reaches production.</p>
    <p><strong>Fix:</strong> bind the enclosing form too (<code>&lt;form action=\${saveAll}&gt;</code>), which is what supplies <code>method="post"</code> and the enctype. Run <code>webjs check</code> to find it: the <code>submitter-needs-bound-form</code> rule reads every template in the app at once, so it resolves the enclosing form across module boundaries and transitively through intermediate components. It is conservative and stays silent when a tag is rendered in a bound form somewhere and an unbound one elsewhere, so a clean check is not by itself proof the form is bound. Two runtime signals back it up: in dev the browser console carries one <code>[webjs]</code> error at submit time naming the fix, and in production the <code>onError</code> hook receives the fingerprint with <code>err.code === 'WEBJS_FORM_SUBMITTED_AS_GET'</code>. The 405 case has its own code, <code>WEBJS_FORM_ACTION_MISSING</code>. Neither changes the response.</p>

    <h2>A render fails on a button's formmethod or formenctype</h2>
    <p><strong>Symptom:</strong> a page that renders fine with JavaScript on fails at render with <code>&lt;button formenctype="text/plain"&gt; inside a bound &lt;form action=\${action}&gt; cannot work</code>, or the same message naming <code>formmethod</code>.</p>
    <p><strong>Cause:</strong> a submitter's <code>formmethod</code> / <code>formenctype</code> overrides the form's own for that button, and a bound action needs a POST body the server can parse as <code>multipart/form-data</code> or <code>application/x-www-form-urlencoded</code>. A GET sends no body at all, and <code>text/plain</code> is flagged by the HTML spec as not intended for machine parsing. Either one submits fine with JavaScript (the client router posts <code>FormData</code> and ignores the attribute) and is a bare <code>405</code> without it, so it is refused at render rather than shipped as a form that works one way only. The check runs on EVERY submitter inside a bound form, whether or not that button binds an action of its own, which is why it can fire on a button you never touched.</p>
    <p><strong>Fix:</strong> drop the attribute and let the form's own <code>method="post"</code> and enctype apply, which is what the renderer already supplies. If the button was meant to go somewhere else entirely, give it a plain <code>formaction="/url"</code>; that retargets the submission away from the bound action and its own <code>formmethod</code> is then left alone. A <code>formmethod="dialog"</code> button is never refused either, because it dismisses a <code>&lt;dialog&gt;</code> instead of submitting.</p>

    <h2>A form re-renders asking you to submit again</h2>
    <p><strong>Symptom:</strong> a submission comes back at 422 with a message about the page having been updated, and the typed values still filled in.</p>
    <p><strong>Cause:</strong> the identity the form submitted names an action file this build does not have. That is deploy skew: the form was rendered by an older build and submitted against a newer one, so the hash no longer resolves. Re-rendering the page is the deliberate answer, because a 404 would discard everything typed and a silent success would report a write that never happened.</p>
    <p><strong>Fix:</strong> nothing to fix; submitting again works, and the values are still there. If you see it constantly rather than around a deploy, check that the app is not being served by two processes on different builds.</p>

    <h2>A reflected attribute is missing, with a warning that the property holds a function</h2>
    <p><strong>Symptom:</strong> a property declared <code>reflect: true</code> renders no attribute at all, and the console carries <code>reflect:true property "x" on &lt;my-tag&gt; holds a function (or an array carrying one), which has no HTML attribute representation</code>. The warning appears in the server log for an SSR render and in the browser console for a client-side assignment, since both run the same reflection path.</p>
    <p><strong>Cause:</strong> the property was assigned a function, and a function has no HTML attribute representation. Writing one anyway is worse than dropping it. <code>String(fn)</code> is the function's SOURCE, so a reflected <code>'use server'</code> action would put its whole body, closure secrets included, into the HTML every visitor downloads, and an <code>Object</code>-typed or <code>Array</code>-typed property would get <code>JSON.stringify(fn)</code>, which is <code>undefined</code> and lands in the attribute as that literal four-character string. So reflection treats a function like <code>null</code> and removes the attribute. This is not specific to a property named <code>action</code>; it holds for every name, because the leak was the generic reflection path stringifying whatever it was handed.</p>
    <p><strong>Fix:</strong> decide what the attribute was for. If the function was meant as a callback, drop <code>reflect</code> from the declaration and keep it as a plain property or a signal, which is where a function belongs. If the attribute is genuinely wanted, assign a string that names the behaviour rather than the function itself. If you own the serialization and know what you are doing, a custom <code>converter.toAttribute</code> runs before this guard and is left alone, so it still receives the function and decides for itself. To bind a server action to a form, use <code>&lt;form action=\${importedAction}&gt;</code>, which resolves the action's identity instead of stringifying it. See <a href="/docs/components">Components</a>.</p>

    <h2>An error saying <code>static properties</code> is no longer supported</h2>
    <p><strong>Symptom:</strong> a component throws at construction with <code>static properties is no longer supported. Declare reactive properties via the factory instead</code>.</p>
    <p><strong>Cause:</strong> the class body has a hand-written <code>static properties = { ... }</code> field. WebJs declares reactive properties only through the <code>WebComponent({ ... })</code> base-class factory now, and the runtime throws on a direct <code>static properties</code>.</p>
    <p><strong>Fix:</strong> move the properties into the factory call (<code>class X extends WebComponent({ count: Number })</code>). Use the <code>prop()</code> helper for options (<code>prop(Number, { reflect: true })</code>) and set defaults in the constructor. Delete the <code>static properties</code> block and any matching <code>declare</code> fields. See <a href="/docs/components">Components</a>. The <code>no-static-properties</code> check rule flags this ahead of the runtime throw.</p>

    <h2>A component's first paint is empty until JavaScript runs</h2>
    <p><strong>Symptom:</strong> a component shows a blank or skeleton state on first load and fills in only after hydration, and with JavaScript disabled it stays empty.</p>
    <p><strong>Cause:</strong> initial data is fetched in <code>connectedCallback</code> or <code>firstUpdated</code>, neither of which runs during SSR, so the server-rendered HTML is empty by design. This breaks progressive enhancement.</p>
    <p><strong>Fix:</strong> fetch the data on the server in the page function and pass it down as a prop (<code>.prop=\${richObject}</code> for a custom element, which round-trips through SSR, or an attribute for a native element). Reserve <code>connectedCallback</code> for genuinely browser-only refinement. See <a href="/docs/progressive-enhancement">Progressive Enhancement</a>.</p>

    <h2>A whole page gets replaced on a frame navigation</h2>
    <p><strong>Symptom:</strong> clicking a link inside a <code>&lt;webjs-frame&gt;</code> replaces the entire document instead of just the frame (for example an auth redirect returning a login page).</p>
    <p><strong>Cause:</strong> the navigation response did not contain a <code>&lt;webjs-frame&gt;</code> with the requested id. Rather than silently swapping the whole document, WebJs now fires a cancelable <code>webjs:frame-missing</code> event and leaves the frame unchanged (with a console warning).</p>
    <p><strong>Fix:</strong> make sure the response for a frame-scoped navigation includes the matching frame, or listen for <code>webjs:frame-missing</code> on <code>document</code> and decide the outcome yourself (the event detail carries <code>{ frameId, url, document }</code>; call <code>preventDefault()</code> to take over, for example a full navigation with <code>navigate(detail.url)</code>). See the <code>&lt;webjs-frame&gt;</code> section in <a href="/docs/client-router">Client Router</a>.</p>

    <h2>A vendor module 404s after deploying under a sub-path</h2>
    <p><strong>Symptom:</strong> the app works at the origin root but, when mounted under a sub-path (example.com/app/) behind a proxy that does not strip the prefix, the importmap and module URLs 404 and the page never hydrates.</p>
    <p><strong>Cause:</strong> the framework-emitted URLs (importmap targets, the boot module specifiers, the RPC endpoint) default to origin-root paths.</p>
    <p><strong>Fix:</strong> set <code>"webjs": { "basePath": "/app" }</code> in <code>package.json</code>. WebJs strips the prefix at ingress and prefixes every framework-emitted URL, so module resolution works under the mount. See <a href="/docs/configuration">Configuration</a>.</p>

    <h2>A browser <code>import</code> of an app file returns 404</h2>
    <p><strong>Symptom:</strong> a module the browser tries to fetch returns 404 even though the file exists.</p>
    <p><strong>Cause:</strong> only files reachable from a browser-bound entry (a page, layout, error, loading, not-found, or component) through the static import graph are servable. A file nothing client-side imports, a hand-rolled <code>scripts/</code> helper, or a <code>.server</code> file's source returns 404 by construction, the same posture as a bundler manifest.</p>
    <p><strong>Fix:</strong> import the module from a browser-bound entry so it enters the graph, or, if it is server-only, keep it behind the <code>.server</code> boundary and reach it through an action. See <a href="/docs/no-build">No-Build Model</a>.</p>

    <h2>A REST endpoint for a server action 404s</h2>
    <p><strong>Symptom:</strong> a <code>'use server'</code> action is RPC-callable from a component but <code>curl</code>ing a path returns 404.</p>
    <p><strong>Cause:</strong> a server action is reachable over RPC, not over an arbitrary REST path on its own. REST endpoints go through <code>route.ts</code> (the framework's HTTP handler).</p>
    <p><strong>Fix:</strong> add an <code>app/&lt;path&gt;/route.ts</code> that imports the action and calls it, or wrap it with the <code>route()</code> adapter from <code>@webjsdev/server</code> (<code>export const POST = route(myAction)</code>). See <a href="/docs/server-actions">Server Actions</a>.</p>

    <h2>A component's <code>static styles</code> have no effect (and a console warning)</h2>
    <p><strong>Symptom:</strong> a <code>static styles = css\`...\`</code> block does not style the component at all, and the framework warns at runtime.</p>
    <p><strong>Cause:</strong> <code>static styles</code> is adopted through a shadow root, but the component is in light DOM (the default), which has no shadow root, so the stylesheet is never adopted and the framework warns.</p>
    <p><strong>Fix:</strong> add <code>static shadow = true</code> to scope the styles, or use Tailwind utilities (unique by construction), or, if you keep custom CSS in light DOM, prefix every class selector with the component tag name (framework invariant 7 for light-DOM CSS). See <a href="/docs/styling">Styling</a>.</p>

    <h2>A vendored package throws "X is not exported" or a missing-symbol error at runtime</h2>
    <p><strong>Symptom:</strong> two npm packages that work together locally throw at runtime in the browser, typically a missing-export or undefined-symbol error from one package reaching into another (for example <code>@codemirror/lint</code> calling into a <code>@codemirror/view</code> that is pinned an older minor than it needs).</p>
    <p><strong>Cause:</strong> the importmap pins each package to one version, and one pinned package declares a dependency or peer range on another pinned package that the pinned version does not satisfy. The graph is INCOHERENT: package A needs <code>view ^6.42.0</code> but the importmap pins <code>view@6.39.16</code>, so a symbol A expects is absent from the older bundle. This can come from a hand-edited <code>.webjs/vendor/importmap.json</code>, a partial vendor pin, or a stale resolve.</p>
    <p><strong>Fix:</strong> run <code>webjs doctor</code>. The importmap-coherence check inspects the produced importmap (the live one AND the vendored <code>.webjs/vendor/importmap.json</code>, with the same verdict for the same dependency set) and warns naming both packages, the required range, and the pinned version. Align the versions: re-run <code>webjs vendor pin</code> to re-resolve a coherent set, or bump the lagging package in <code>package.json</code> and reinstall so the importmap pins a version every dependent accepts. See <a href="/docs/no-build">No-Build Model</a>.</p>

    <h2>A <code>webjs.dev.before</code> / <code>webjs.start.before</code> step fails and aborts the boot</h2>
    <p><strong>Symptom:</strong> the dev or prod server refuses to start, printing <code>webjs dev: before-step failed (exit N): &lt;command&gt;</code> (or <code>webjs start: ...</code>) and never serving.</p>
    <p><strong>Cause:</strong> a <code>webjs.dev.before</code> / <code>webjs.start.before</code> step (the scaffold ships <code>webjs db migrate</code>) exited non-zero. As of #550, <code>webjs dev</code> / <code>webjs start</code> run these one-shot steps to completion BEFORE serving (replacing the old <code>predev</code> / <code>prestart</code> npm hooks), and they ABORT the boot on a failure so the app never serves a stale client or schema. A bare <code>webjs dev</code> and <code>npm run dev</code> run the same steps, so this is not a "wrong command" problem.</p>
    <p><strong>Fix:</strong> run the failing command directly to read its real error (for the scaffold's steps, <code>webjs db generate</code> or <code>webjs db migrate</code>), fix the cause (a malformed <code>db/schema.server.ts</code>, an unreachable <code>DATABASE_URL</code>), then re-run. A local binary in a step (<code>drizzle-kit</code>, <code>tailwindcss</code>) resolves under a bare <code>webjs dev</code> the same way <code>npm run</code> resolves it (the ancestor <code>node_modules/.bin</code> dirs are on the step's PATH).</p>

    <h2>A <code>'use server'</code> file's exports are not callable from a component</h2>
    <p><strong>Symptom:</strong> you added <code>'use server'</code> to a plain <code>.ts</code> file and imported one of its functions into a component, but the call fails or <code>webjs check</code> flags <code>use-server-needs-extension</code>.</p>
    <p><strong>Cause:</strong> the RPC boundary keys on the FILE EXTENSION, not the directive alone. A <code>'use server'</code> directive in a plain <code>.ts</code> file is a lint violation, because the file router only treats <code>.server.{js,ts}</code> files as the server boundary. Without the extension the source would also be served to the browser.</p>
    <p><strong>Fix:</strong> rename the file to <code>*.server.ts</code>. The extension makes it server-only (source-protected) and the <code>'use server'</code> directive makes its exports RPC-callable. See <a href="/docs/server-actions">Server Actions</a>. The <code>use-server-needs-extension</code> check rule catches this, and <code>use-server-exports-callable</code> flags a <code>'use server'</code> file that exports no callable function (it registers nothing, so the RPC 404s silently).</p>

    <h2>A configured server action file with more than one function is rejected</h2>
    <p><strong>Symptom:</strong> <code>webjs check</code> flags <code>one-action-per-configured-file</code> on a <code>*.server.ts</code> that exports a config (<code>method</code>, <code>cache</code>, <code>validate</code>, <code>middleware</code>) alongside two callable functions.</p>
    <p><strong>Cause:</strong> the HTTP-verb and caching config exports (<code>export const method</code>, <code>cache</code>, <code>tags</code>, <code>invalidates</code>, <code>validate</code>, <code>middleware</code>) attach to the ONE action in the file, so a second callable function makes the config ambiguous.</p>
    <p><strong>Fix:</strong> keep one callable function per configured action file (the convention is one function per action file regardless). Split the second function into its own <code>*.server.ts</code>. See <a href="/docs/server-actions">Server Actions</a>. The <code>one-action-per-configured-file</code> check rule enforces this.</p>

    <h2>A nested layout or page's <code>&lt;html&gt;</code> shell is dropped</h2>
    <p><strong>Symptom:</strong> you wrote <code>&lt;!doctype&gt;</code> / <code>&lt;html&gt;</code> / <code>&lt;head&gt;</code> / <code>&lt;body&gt;</code> in a non-root layout or a page and the tags vanish from the output, or <code>webjs check</code> flags <code>shell-in-non-root-layout</code>.</p>
    <p><strong>Cause:</strong> the framework auto-emits the document shell around the whole composition, so only the ROOT layout (<code>app/layout.ts</code> exactly) may write its own shell. A nested shell ends up inside the framework's <code>&lt;body&gt;</code> and the HTML parser drops the stray tags.</p>
    <p><strong>Fix:</strong> remove the shell tags from the nested layout or page and return just the content. Move any <code>&lt;html lang&gt;</code> / <code>&lt;body class&gt;</code> customization to the root layout, which the framework respects and splices its required tags into. See <a href="/docs/routing">Routing</a>. The <code>shell-in-non-root-layout</code> check rule flags this, framework invariant 8.</p>

    <h2>An import of a symbol crashes at runtime, but the checker was green</h2>
    <p><strong>Symptom:</strong> a named import resolves to <code>undefined</code> and crashes on first use (often after renaming or removing a schema table), and type-checking reports <code>has no exported member</code> while the correctness checker passed.</p>
    <p><strong>Cause:</strong> most check rules are elision-based and do not compile types, so a stale import used to slip past. Dropping the example <code>todos</code> table while another module still imported it is the canonical case.</p>
    <p><strong>Fix:</strong> add the missing export, correct the imported name, or remove the import (and prune any orphaned module). The <code>no-missing-local-import</code> rule now flags a named value import of a symbol a resolvable app-internal module does not export, so it is caught before runtime. It is conservative by design (only app-internal specifiers, only named value imports, and it skips a module whose exports are not fully enumerable), so a re-export barrel and a <code>'use server'</code> action file resolve normally. Type-checking alongside the correctness checker stays the belt-and-suspenders habit.</p>

    <h2>Still stuck</h2>
    <p>The framework source is in <code>node_modules/@webjsdev/</code> with no build step, so what you read is what runs. Grep the relevant file (the SSR pipeline in <code>@webjsdev/server/src/ssr.js</code>, client hydration in <code>@webjsdev/core/src/render-client.js</code>, the convention rules in <code>@webjsdev/server/src/check.js</code>). Run <code>webjs check</code> to surface most of the issues above before they reach the browser, and run <code>webjs check --rules</code> to read what each rule enforces.</p>
  `;
}
